### ISSUE TITLE
Exceptions in Apktool 2.2.0

### ISSUE THREAD

**Issue by ezesoler** [suraj-root/spade#1]
I got an error when I compile and I can not know why.

> Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_7866777157350481778.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 71411662, --version-name, v1.16.62, -F, /tmp/APKTOOL2764605009534321415.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Escritorio/GitHub/spade/piriform/res, -M, /root/Escritorio/GitHub/spade/piriform/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_7866777157350481778.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 71411662, --version-name, v1.16.62, -F, /tmp/APKTOOL2764605009534321415.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Escritorio/GitHub/spade/piriform/res, -M, /root/Escritorio/GitHub/spade/piriform/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_7866777157350481778.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 71411662, --version-name, v1.16.62, -F, /tmp/APKTOOL2764605009534321415.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Escritorio/GitHub/spade/piriform/res, -M, /root/Escritorio/GitHub/spade/piriform/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_7866777157350481778.tmp": error=2, No existe el fichero o el directorio
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No existe el fichero o el directorio
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
[*] Signing apk...
java.io.FileNotFoundException: piriform/dist/piriform.apk (No existe el fichero o el directorio)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.jar.JarFile.<init>(JarFile.java:154)
	at java.util.jar.JarFile.<init>(JarFile.java:133)
	at orig.SignApk.main(SignApk.java:488)

The error is apktool and is common but can not identify what the problem

Sorry for my bad English

**Comment by ezesoler** [comment]
Sorry i'm sure it's a problem with my configuration apktool but maybe someone knows how to fix it.

**Comment by suraj-root** [comment]
The problem is with apktool, i think it couldn't back-smali the injected hook to a standalone application package, try with a new downloaded apk off the playstore, might work, and also check for filenames, makes sure if its correct.

**Comment by ezesoler** [comment]
The problem is that not have these libraries: lib32stdc++6, lib32ncurses5 and lib32z1. 

Now everything worked perfect. Thanks for your answer!

**Comment by suraj-root** [comment]
Glad it worked for you
