### ISSUE TITLE
Building resources exception error

### ISSUE THREAD

**Issue by benichmt1** [suraj-root/spade#3]
Ran into a strange issue on latest Kali 2.0.

Backdooring an app created with CoronaSDK.
```
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_127493273813439988.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0.0, -F, /tmp/APKTOOL7965027217118973156.tmp, -0, xml, -0, dex, -0, arsc, -0, md, -0, txt, -0, car, -0, ttf, -0, so, -0, lib/armeabi-v7a/libjnlua5.1.so, -0, html, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /opt/spade/SecureState/res, -M, /opt/spade/SecureState/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_127493273813439988.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0.0, -F, /tmp/APKTOOL7965027217118973156.tmp, -0, xml, -0, dex, -0, arsc, -0, md, -0, txt, -0, car, -0, ttf, -0, so, -0, lib/armeabi-v7a/libjnlua5.1.so, -0, html, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /opt/spade/SecureState/res, -M, /opt/spade/SecureState/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_127493273813439988.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0.0, -F, /tmp/APKTOOL7965027217118973156.tmp, -0, xml, -0, dex, -0, arsc, -0, md, -0, txt, -0, car, -0, ttf, -0, so, -0, lib/armeabi-v7a/libjnlua5.1.so, -0, html, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /opt/spade/SecureState/res, -M, /opt/spade/SecureState/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_127493273813439988.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
```

**Comment by benichmt1** [comment]
Was an issue with one of the dependencies which fixed the issue.

**Comment by mrpr1mus** [comment]
Same error here, how did you solved?

**Comment by benichmt1** [comment]
@mrpr1mus 
I installed the dependencies on Kali by doing the following:
<code> apt-get lib32stdc++6 lib32ncurses5 lib32z1. </code>
